package cn.yfyue.sysauth.mapper;

import cn.yfyue.sysauth.model.TApiLog;

public interface TApiLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_API_LOG
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_API_LOG
     *
     * @mbg.generated
     */
    int insert(TApiLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_API_LOG
     *
     * @mbg.generated
     */
    int insertSelective(TApiLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_API_LOG
     *
     * @mbg.generated
     */
    TApiLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_API_LOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TApiLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_API_LOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TApiLog record);
}